### ISSUE TITLE
v1.5

### ISSUE THREAD

**Issue by gao-sun** [gao-sun/eul#102]
### Features
- [x] CPU Graph #31
- [x] Replace pipe with one-off execution for `nettop` to avoid potential high CPU usage #35 
- [x] Choose what to display in status bar for each component #8 
- [x] Show memory as usage percentage in the bar #90 
- [x] Show load average in CPU section #65 
- [x] Provide option to hide from status bar #104 
- [x] Provide option to choose which fan(s) to display

**Comment by gao-sun** [comment]
guys, too busy these days. got some time to breathe this weekend. stay tuned. cheers!

**Comment by gao-sun** [comment]
I'm back. Cyberpunk 2077 fascinated me too much.
