### ISSUE TITLE
v1.6

### ISSUE THREAD

**Issue by gao-sun** [gao-sun/eul#134]
Back from hard work and night city. :-)

- [ ] <del>Add cpu frequency related data (hard) #48</del>
- [x] Show storage usage per disk and recognize external devices along with eject button #105
- [x] Battery status of bluetooth devices #69
- [x] Show top ram programs #81 
- [x] GPU utilization #93
- [x] Provide manual network interface selection #85
- [x] Style Light and Dark independently from macOS style #159
