### ISSUE TITLE
v1.7

### ISSUE THREAD

**Issue by gao-sun** [gao-sun/eul#212]
- [ ] #48 Add cpu frequency related data
- [ ] #163 Export temperature/stats data into csv
- [ ] #190 Add swap memory display
- [ ] #194 Add disk activity widget
- [ ] #205 Bluetooth devices battery on menubar
- [ ] #207 CPU icon shows architecture
- [ ] #211 Show graph for Network and larger graphs on hover in dropdown

**Comment by betterlmy** [comment]
How's the progress? it's going to be the Spring Festival.
